# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: "gcc:latest"
    steps:
      - checkout
      - run:
          name: Install CMAKE
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Testing
          command: 'cd ./bin && ./lifeguards'
      - run:
          name: Testing 2
          command: 'cd ./bin && ./lifeguards'
workflows:
   version: 2
   build_on-push:
     jobs:
       - build
   build_every_5:
     triggers:
       - schedule:
           cron: "* * * 5 *"
           filters:
             branches:
               only:
                 - master
                 - hotfix2
     jobs:
       - build
